version: 2.1

orbs:
  node: circleci/node@4.7.0
  #aws-ecr: circleci/aws-ecr@6.13.0
  #aws-ecs: circleci/aws-ecs@1.12.0

executors:
  node-executor:
    docker:
      - image: circleci/node:16
    working_directory: /tmp/project

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: build react app
          command: yarn build
      # - run:
      #     name: Create directory with permissions and list contents
      #     command: |
      #       mkdir -p -m 777 /tmp/project/workspace/build
      #       echo "Checking contents before persisting:"
      #       ls -la /tmp/project
      #       ls -la /tmp/project/workspace
      - persist_to_workspace:
          root: /tmp/project
          paths:
            - .

  build_docker_image:
    executor: node-executor
    steps: 
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_cache: true
      - run:
          name: List contents of root directory
          command: ls -la
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/project
      - run:
          name: List contents after attaching workspace
          command: |
            echo "Listing contents after attaching workspace:"
            ls -la /tmp/project
            # ls -la /tmp/project/Dockerfile  # Verify Dockerfile exists
      - run:
          name: create one folder
          command: mkdir -p /tmp/temp_build
      - run:
          name: copy build from workspace
          command: cp -r /tmp/project/build /tmp/temp_build/
      - run:
          name: Copy build files to the current directory
          command: cp -r /tmp/temp_build/* ./build/
      - store_artifacts: #will store the build yarn file inside this
          path: ./build
          destination: /build_artifacts
      - run:
          name: build docker image
          command: docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
        #654654612003.dkr.ecr.us-east-1.amazonaws.com/ecr_react_repo

workflows:
  version: 2
  build_and_docker_image:
    jobs:
      - build
      - build_docker_image:
          requires:
            - build
