version: 2.1

orbs:
  node: circleci/node@4.7.0
  #aws-ecr: circleci/aws-ecr@6.13.0
  #aws-ecs: circleci/aws-ecs@1.12.0

executors:
  node-executor:
    docker:
      - image: circleci/node:16
    working_directory: ~/project

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Create workspace and build directories
          command: |
            mkdir -p ~/project/workspace/build
      - run:
          name: Create dummy build file
          command: echo "Hello, world!" > ~/project/workspace/build/dummy.txt
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: build react app
          command: yarn build
      - run:
          name: List contents before persisting
          command: ls -la ~/project/workspace/build
      - persist_to_workspace:
          root: ~/project
          paths:
            - workspace/build

  build_docker_image:
    executor: node-executor
    steps: 
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_cache: true
      - run:
          name: List contents of root directory
          command: ls -la
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/project/workspace
      - run:
          name: List contents of attached workspace
          command: ls -la ~/project/workspace/build
      - run:
          name: copy build from workspace
          command: cp -r ~/project/workspace/build ./build
      - run:
          name: build docker image
          command: docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
        #654654612003.dkr.ecr.us-east-1.amazonaws.com/ecr_react_repo

workflows:
  version: 2
  build_and_docker_image:
    jobs:
      - build
      - build_docker_image:
          requires:
            - build
