version: 2.1

orbs:
  node: circleci/node@4.7.0
  #aws-ecr: circleci/aws-ecr@6.13.0
  #aws-ecs: circleci/aws-ecs@1.12.0

executors:
  node-executor:
    docker:
      - image: circleci/node:16

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: build react app
          command: yarn build
      - run:
          name: List build directory
          command: ls -la build
      - persist_to_workspace:
          root: .
          paths:
            - build

  build_docker_image:
    executor: node-executor
    steps: 
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_cache: true
      - run:
          name: List contents of root directory
          command: ls -la
      - attach_workspace:
          at: .
      - run:
          name: List workspace directory
          command: ls -la
      - run:
          name: copy build from workspace
          command: cp -r ./build ./build
      - run:
          name: build docker image
          command: docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
        #654654612003.dkr.ecr.us-east-1.amazonaws.com/ecr_react_repo

workflows:
  version: 2
  build_and_docker_image:
    jobs:
      - build
      - build_docker_image:
          requires:
            - build
