version: 2.1

orbs:
  node: circleci/node@4.7.0
  #aws-ecr: circleci/aws-ecr@6.13.0
  #aws-ecs: circleci/aws-ecs@1.12.0

executors:
  node-executor:
   docker: 
    - image: circleci/node:16


jobs:
  build:
    executor: node-executor
    steps:
     - checkout
     - node/install-packages:
        cache-key: 'yarn.lock'
     - run:
        name: build react app
        command: yarn build
     - persist_to_workspace:
        root: .
        paths:
          - build

workflows:
  version: 2
  build:
    jobs:
      - build

        
